builds:
  - binary: mediumautopost
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: mediumautopost
    homepage: "https://github.com/nadav-legit/brew_test"
    tap:
      owner: nadav-legit
      name: brew_test
    commit_author:
      name: noyna
      email: nadav@legitsecurity.com

checksum:
  name_template: 'checksums.txt'
