# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mediumautopost < Formula
  desc ""
  homepage "https://github.com/nadav-legit/brew_test"
  version "0.0.2"

  on_macos do
    url "https://github.com/nadav-legit/brew_test/releases/download/0.0.2/brew_test_0.0.2_darwin_all.tar.gz"
    sha256 "48b407d5776b3c610cbb9d821f7aca8876e986afa15d90c101cbdad4750a62a6"

    def install
      bin.install "brew_test"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nadav-legit/brew_test/releases/download/0.0.2/brew_test_0.0.2_linux_arm64.tar.gz"
      sha256 "2307bea973cae194945473490776654e7f5fa30dec10859bf3fa01fd29af6899"

      def install
        bin.install "mediumautopost"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nadav-legit/brew_test/releases/download/0.0.2/brew_test_0.0.2_linux_amd64.tar.gz"
      sha256 "c7a3f73785a419cc8dbc9df75ca6affa95e200764c0ea45604700b74e5340af9"

      def install
        bin.install "mediumautopost"
      end
    end
  end
end
