name: goreleaser

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: ${{ env.GITHUB_REF_NAME }}
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
#   homebrew:
#     needs: goreleaser
#     name: Bump Homebrew formula
#     runs-on: macos-latest
#     steps:
#       - uses: dawidd6/action-homebrew-bump-formula@v3
#         with:
#           token: ${{ secrets.PUBLISHER_TOKEN }}
#           tap: nadav-legit/nadav-legit
#           formula: brew_test  release:
  release:
    needs: goreleaser
    runs-on: ubuntu-latest
    outputs:
      brew_release_file: ${{ steps.artifact_name.outputs.brew_release_file }}
    permissions:
      actions: read # To read the workflow path.
      id-token: write # To sign the provenance.
      contents: write # To add assets to a release.
    env:
      ARTIFACTS_DOWNLOAD_PATH: /tmp/macos_archives
    steps:
      - name: create
        run: |
          mkdir ${{ env.ARTIFACTS_DOWNLOAD_PATH }}
          cd "${{ env.ARTIFACTS_DOWNLOAD_PATH }}"
          echo 123456666 > brew_test_darwin_amd64.tar.gz
      - name: Release
        uses: softprops/action-gh-release@d4e8205d7e959a9107da6396278b2f1f07af0f9b
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.ARTIFACTS_DOWNLOAD_PATH }}/*
      - uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # ratchet:actions/upload-artifact@v3
        with:
          name: release_artifacts
          path: ${{ env.ARTIFACTS_DOWNLOAD_PATH }}/*
      - name: brew-inputs
        id: artifact_name
        run: |
          set -euo pipefail
          cd "${{ env.ARTIFACTS_DOWNLOAD_PATH }}"
          echo 123456666 > brew_test_darwin_amd64.tar.gz
          file_name=$(find . -maxdepth 1 -type f -name "*darwin_amd64*" -exec basename {} \;)
          echo "brew_release_file=$file_name" >> $GITHUB_OUTPUT
  bump:   
    needs: release
    runs-on: macos-latest
    env:
          ARTIFACTS_DOWNLOAD_PATH: /tmp/macos_archives
    steps:
    - uses: actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7 # ratchet:actions/download-artifact@v3
      with:
          name: release_artifacts
          path: ${{ env.ARTIFACTS_DOWNLOAD_PATH }}
    - name: Get version
      id: get_version
      run: echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
    - name: Set SHA
      id: shasum
      run: |
        cd ${{ env.ARTIFACTS_DOWNLOAD_PATH }}
        echo "sha=$(shasum -a 256 ${{ needs.release.outputs.brew_release_file }} | awk '{printf $1}')" >> $GITHUB_OUTPUT
    - name: Bump Brew
      env: 
        HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
      run: |
        brew --version
        brew update
        brew tap nadav-legit/nadav-legit
        brew bump-formula-pr -f --version=${{ steps.get_version.outputs.version }} --no-browse --no-audit \
        --sha256=${{ steps.shasum.outputs.sha }} \
        --url="https://github.com/legit-labs/legitify/releases/download/${{ steps.get_version.outputs.version }}/${{ needs.release.outputs.brew_release_file }}" \
        --version=${{ steps.get_version.outputs.version }} \
        nadav-legit/nadav-legit/brew_test
